### ISSUE TITLE
Missing VariableDeclaration in Go

### ISSUE THREAD

**Issue by CodingDepot** [Fraunhofer-AISEC/cpg#1230] opened 2023-07-06 10:25 UTC
When analyzing Go programs using the CPG, there are no `VariableDeclaration`s being created for the shorthand `:=`. Any `DeclaredReferenceExpression` created from this refers to `null`.
Example:
```
package main

func main() {
    name := "firstname lastname"
}
```
Analyzing this program results in no `VariableDeclarations`, but an `AssignExpression` with a `DecrlaredReferenceExpression` on the left hand side, which in turn refers to `null`.

When explicitely declaring variables using the format `var x int` a `VariableDeclaration` is created as expected.

**Comment by oxisto** [comment] 2023-07-13 21:12
Can you check whether the Go Extra Pass is executed? This should create a variable declaration.

https://github.com/Fraunhofer-AISEC/cpg/blob/e524e19b14b41a562de6b457613ea15ecf831736/cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt#L181-184

**Comment by CodingDepot** [comment] 2023-07-17 07:43
It is not automatically executed just by registering the GoLanguage, but manually registering the GoExtraPass seems to solve the issue.

**Comment by oxisto** [comment] 2023-07-17 08:09
> It is not automatically executed just by registering the GoLanguage, but manually registering the GoExtraPass seems to solve the issue.

It should be automatically executed when using `defaultPasses()`, so this seems to a problem of the CloudPG repo then.

**Comment by CodingDepot** [comment] 2023-07-17 08:22
That is weird, since `defaultPasses()` is already being called after all languages are registered, but `GoExtraPass` will still not be executed unless I specifically register it.

**Comment by oxisto** [comment] 2023-07-17 08:24
> That is weird, since `defaultPasses()` is already being called after all languages are registered, but `GoExtraPass` will still not be executed unless I specifically register it.

Hmm ok this sounds weird. Can you push the branch to the CloudPG repo?

**Comment by CodingDepot** [comment] 2023-07-17 08:52
> Hmm ok this sounds weird. Can you push the branch to the CloudPG repo?

I pushed it to the CloudPG-branch `cpg-version-update`.

**Comment by oxisto** [comment] 2023-07-17 12:03
> > Hmm ok this sounds weird. Can you push the branch to the CloudPG repo?
> 
> I pushed it to the new CloudPG-branch `cpg-version-update`.

Even if I comment out your specifically registering of the `GoExtraPass`, the extra pass is still executed automatically. So I cannot reproduce this unfortunately.

**Comment by oxisto** [comment] 2023-07-17 12:15
Ah. The issue is that the go passes in the CloudPG need to specify `@DependsOn(GoExtraPass::class)`, so that the go extra pass is executed *before* them. We also might need #1225 and this will be in 7.0.1, once the build goes through.

**Closed by oxisto** 2023-07-17 12:15 UTC
