### ISSUE TITLE
memberCallExpression is  mistakenly parsed as staticCallExpression due to the package path of import

### ISSUE THREAD

**Issue by z2Z6** [Fraunhofer-AISEC/cpg#1026] opened 2023-01-10 07:03 UTC
# Unexpected behavior
The node type of `test.doSomething` on line 6 is affected by package path on first line. If penultimate package name which ends with `.*` is the same as base name of `memberCallExpression`, then the `memberCallExpression` will be mistakenly parsed as `staticCallExpression`, e.g. node on line 6. Modify package name "test" on first line to others, the node type is parsed as `memberCallExpression` correctly.

# Code of interest
package structure
```
|--com
   |--test
      |--Test.java
|--Sample.java
```
Sample.java
```java
import com.test.*;  // line 1

public class Sample {
    public void func() {
        Test test = new Test();
        test.doSomething();  // line 6
    }
}
```

# Configuration
v5.1.0
```java
new TranslationConfiguration.Builder()
                .sourceLocations(new File(filename))
                .defaultPasses()
                .defaultLanguages()
                .build();
```

**Comment by KuechA** [comment] 2023-01-10 11:19
Hi @z2Z6 ,

thank you for opening the issue. Could you please check if the PR #963 solves the problem by chance? We're currently working on improving the naming system (which is almost done) and afterwards we'll work on the symbol/call resolution since they are related to each other. So please stay tuned :)

**Comment by z2Z6** [comment] 2023-01-12 10:16
> Hi @z2Z6 ,
> 
> thank you for opening the issue. Could you please check if the PR #963 solves the problem by chance? We're currently working on improving the naming system (which is almost done) and afterwards we'll work on the symbol/call resolution since they are related to each other. So please stay tuned :)

Unfortunately, it doesn't seem to work on the `main` branch now. I will open issues I encounter if they can be describled clearly, look forward to the next version.

**Comment by oxisto** [comment] 2023-01-13 23:39
> > Hi @z2Z6 ,
> > thank you for opening the issue. Could you please check if the PR #963 solves the problem by chance? We're currently working on improving the naming system (which is almost done) and afterwards we'll work on the symbol/call resolution since they are related to each other. So please stay tuned :)
> 
> Unfortunately, it doesn't seem to work on the `main` branch now. I will open issues I encounter if they can be describled clearly, look forward to the next version.

I can confirm that this is now definitely fixed in #1031

**Comment by z2Z6** [comment] 2023-01-14 10:39
The problem is solved, thanks.

**Comment by oxisto** [comment] 2023-01-14 13:05
Looks like I can reproduce this even with #1031 under certain cirumstances. I will have another look and add a test to the #1031 PR.

**Comment by z2Z6** [comment] 2023-01-16 09:13
Hi @oxisto, 
There seem to be another problem, if `Sample.java` is in the package path which is the same as `Test.java`. In this case, there is no need to import package path of `Test.java` for `Sample.java`.

 package structure
```java
|--com
   |--Test.java
   |--Sample.java
```
Sample.java
```java
package com;

public class Sample {
    public void func() {
        Test.doSomething();  // The attribute `isStatic` of MemberCallExpression is false
    }
}
```

**Comment by oxisto** [comment] 2023-01-16 12:38
> Hi @oxisto, There seem to be another problem, if `Sample.java` is in the package path which is the same as `Test.java`. In this case, there is no need to import package path of `Test.java` for `Sample.java`.
> 
> package structure
> 
> ```java
> |--com
>    |--Test.java
>    |--Sample.java
> ```
> 
> Sample.java
> 
> ```java
> package com;
> 
> public class Sample {
>     public void func() {
>         Test.doSomething();  // The attribute `isStatic` of MemberCallExpression is false
>     }
> }
> ```

Interesting. Seems this a different, but related issue. Could you maybe open a second issue for this specifically? I do not want to have too many problems in one single issue :)

**Closed** 2023-01-16 14:44 UTC
Labels: bug, java

**Comment by z2Z6** [comment] 2023-01-17 02:34
The issue is opened in #1041.
