### ISSUE TITLE
Anonymous classes in Java not translated to RecordDeclaration

### ISSUE THREAD

**Issue by seelchen** [Fraunhofer-AISEC/cpg#1005] opened 2022-12-02 16:14 UTC
# Unexpected behavior

When analyzing C++ code, an anonymous class is translated into a RecordDeclaration.
However, when analyzing Java code with an anonymous class, the anonymous class is only translated into a DeclarationStatement but not further into a RecordDeclaration. This means that implemented or overridden methods in the anonymous class cannot be analyzed.

# Example

```
interface HelloWorld {
	public void greet();
}

class Anonymous {

	public static void main() {
		HelloWorld frenchGreeting = new HelloWorld() {
			public void greet() {
				System.out.println("tout le monde");
			}
		};

		frenchGreeting.greet();
	}
}
```

# Changes to the configuration

```
TranslationConfiguration.builder()
            .defaultPasses()
            .defaultLanguages()
            .codeInNodes(true)
```

**Comment by oxisto** [comment] 2022-12-02 16:39
Sort of duplicate of https://github.com/Fraunhofer-AISEC/cpg/issues/10. In the meantime, we had basic support for it in C++, but not in Java and only in the form of a FunctionDeclaration without any name, which can cause problems in the DFG and EOG.

**Closed** 2023-03-01 19:16 UTC
