### ISSUE TITLE
Incorrect parsing of nested casts and unary operators in the CXX language frontend

### ISSUE THREAD

**Issue by KuechA** [Fraunhofer-AISEC/cpg#1347] opened 2023-10-27 08:52 UTC
# Unexpected behavior

A BinaryOperation `&` with lhs CastExpression(int64_t) and rhs x is generated instead of a CastExpression of the UnaryOperator `&` with input `x`

# Code of interest

```
(int64_t)&x
```

**Comment by morbitzer** [comment] 2023-10-30 16:39
A similar error occurs with this code:

`*(int64_t *)outptr = *(int64_t *)&key;`

Were are missing the connection between the cast and `&`

![graph](https://github.com/Fraunhofer-AISEC/cpg/assets/13377683/a0a2e724-789a-4192-909a-2a3afabaf0a1)

**Comment by oxisto** [comment] 2023-11-15 13:54
I think I know the culprit. It is in the way we replace calls with casts; which is currently broken because of the way we iterate the AST when doing so. I have a similar problem in the Go frontend. I will have a look at this.

**Comment by oxisto** [comment] 2023-11-15 17:51
Unfortunately, I cannot reproduce either issue. If I parse these code snippets here:

```c
typedef long int64_t;
int x = 1;
int y = (int64_t) &x;

int main() {
  long key;
  long outptr;
  *(int64_t *)outptr = *(int64_t *)&key;
}
```

They correctly parse as a cast to a unary expression to `x`. And I have a dataflow from `key` to the `*` unary expression.

Are you defining `int64_t` at some point? A potential issue is that while the CPG "knows" that this one of the standard-ish types, the underlying C/C++ parser CDT will only parse this correctly as a type if you either include the contents of `stdint.h` or typedef it our self. This is actually the "correct" way to do that per C standard, since it is not a built-in type, but a type of the standard library.

**Comment by oxisto** [comment] 2023-11-20 21:07
I can finally reproduce this, when I turn on `guessCastExpressions`. Fix is incoming.

**Closed** 2023-11-21 08:42 UTC
Labels: cxx
